### ISSUE TITLE
how to Install Python 3.6+, then run `pip install byml` issue

### ISSUE THREAD

**Issue by User198263321** [leoetlino/byml-v2#7]
I installed python 3.8 and now how am I suppose to use that command? I'm new to python shells and when I put in pip install byml it throws an error. trying it in cmd also throws an error
![image](https://user-images.githubusercontent.com/53535277/78083805-89067300-7384-11ea-8bb6-73e714c1786c.png)

Am I missing something? Also do I just drag the files to the python script after I do this and it simply works?

I'm trying to convert from .byml to .yml to view animal crossing new horizons textures.

Thanks!

**Comment by leoetlino** [comment]
`pip install byml` should be run in your system shell, not in the Python shell, since it's not a Python command.

If you're on Windows, you might need to run `py -m pip install byml` instead.

FWIW https://zeldamods.org/wiki/Help:CLI has more information on how to use the command line if you're interested!

>I'm trying to convert from .byml to .yml to view animal crossing new horizons textures.

Textures aren't stored in BYML files. BYML files are typically used to store parameter data, not graphical assets like models or textures. Are you sure you aren't looking for BFRES instead? [Switch Toolbox](https://github.com/KillzXGaming/Switch-Toolbox) should be able to let you visualize models.
